[package]
name = "tiktok-tts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
dotenvy = "0.15.7"
sailfish = "0.8.3"
serde = "1.0.198"
sqlx = { version = "0.7.4", features = ["postgres", "runtime-tokio"] }
tokio = "1.37.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18" }
rand = "0.8.5"
metrics = "0.22.3"
metrics-exporter-prometheus = "0.14.0"
rust-embed = { version = "8.3.0", features = ["include-exclude"]}
mime_guess = "2.0.4"
tower-http = { version = "0.5.2", features = ["compression-gzip", "compression-deflate"]}
reqwest = { version = "0.12.4", features = ["json"] }
lazy_static = "1.4.0"
urlencoding = "2.1.3"
base64_light = "0.1.5"
futures = "0.3.30"
once_cell = "1.19.0"
